if(NOT LA_COMPANY_NAME)
	set(LA_COMPANY_NAME "L-Acoustics")
endif()

if(NOT LA_COMPANY_URL)
	string(TOLOWER "https://github.com/L-Acoustics/avdecc" LA_COMPANY_URL)
endif()

if(NOT LA_PROJECT_CONTACT)
	string(TOLOWER "software@l-acoustics.com" LA_PROJECT_CONTACT)
endif()

if(CMAKE_HOST_APPLE)
	if(NOT LA_TEAM_IDENTIFIER AND ENABLE_AVDECC_SIGNING)
		message(FATAL_ERROR "Required variable LA_TEAM_IDENTIFIER not defined before including CommonProjectProperties.cmake.")
	endif()
endif()

if(WIN32)
	find_program(DOT_PROGRAM "dot")
	if(NOT DOT_PROGRAM)
		message(STATUS "Graphviz's 'dot' not found in the path. Make sure it's installed and in the path if you want class graph in Doxygen. Download it from http://www.graphviz.org/")
		set(HAVE_DOT "NO")
	else()
		set(HAVE_DOT "YES")
	endif()
else()
	set(HAVE_DOT "NO")
endif()

set(LA_PROJECT_COMPANYNAME "${LA_COMPANY_NAME}")
set(LA_PROJECT_LEGALCOPYRIGHT "(c) ${LA_COMPANY_NAME} and its contributors")
string(TIMESTAMP LA_YEAR %Y)
set(LA_PROJECT_READABLE_COPYRIGHT "Copyright 2016-${LA_YEAR}, ${LA_COMPANY_NAME} and its contributors")
set(LA_PROJECT_URLABOUTINFO "${LA_COMPANY_URL}")
