name: Format

on :
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev ]
    paths-ignore:
      - 'Docker'
      - '**/README.md'
      - '**/LICENCE'

env:
  INCLUDE_LINUX: true
  INCLUDE_WINDOWS: true
  INCLUDE_MACOS: true

jobs:
  fix-files:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install job dependencies
      shell: bash
      run: |
        choco install -y dos2unix
        curl https://www.kikisoft.com/Hive/clang-format/clang-format-7.0.0-LambdaPatch-windows.exe -o clang-format.exe
        ln -s $(pwd)/clang-format.exe /usr/bin/clang-format

    - name: Run fix_files
      shell: bash {0}
      run: |
        ./scripts/bashUtils/fix_files.sh

    - name: Check for changes
      shell: bash
      run: |
        git diff --name-status --exit-code
        if [ $? -ne 0 ]; then
          echo "Some files need formatting/fixing. Please run the script and commit the changes."
          exit 1
        fi

  build-test-linux:
    uses: ./.github/workflows/linux.yml
    if: ${{ github.event_name == 'pull_request' }}
    needs: fix-files
  build-test-windows:
    uses: ./.github/workflows/windows.yml
    if: ${{ github.event_name == 'pull_request'   }}
    needs: fix-files
  build-test-macos:
    uses: ./.github/workflows/macos.yml
    if: ${{ github.event_name == 'pull_request' }}
    needs: fix-files

